# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-05 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='geo_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
