# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tracker', '0002_auto_20171205_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_date', models.DateTimeField(auto_now_add=True)),
                ('going', models.BooleanField(default=True)),
                ('picked_time', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tracker.Profile')),
            ],
        ),
    ]
