# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tracker', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('U', 'Unknown'), ('C', 'Close By'), ('A', 'Accident')], default='U', max_length=1)),
                ('alerted', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_tracker.Profile')),
            ],
        ),
    ]
