# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tracker', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='closeby_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
